from sys import stdout

with open('checklist.txt', 'r') as file:
    checklist = [line.strip() for line in file]

def hill(inpt,q,r,s,t):
	lst = []
	otpt = []

	for letter in inpt:
		lst.append(str(ord(letter)-97))

	n = 0
	while n < len(inpt):
		det = float(q*t-r*s)
		indet = 1
		for w in range(1,26):
			if w*det % 26 == 1:
				indet = w
		x = int(lst[n])
		y = int(lst[n+1])
		a = (t % 26)*indet % 26
		b = (-r % 26)*indet % 26
		c = (-s % 26)*indet % 26
		d = (q % 26)*indet % 26
		otpt.append(chr(((a*x+b*y) % 26)+97))
		otpt.append(chr(((c*x+d*y) % 26)+97))
		n+=2

	return ''.join(otpt)


inpt = 'IBWUQRCIHAQVILUDSARREAVXDDQCIFXZPLXZLDFXCIJODRENULGKULVNVHJOCSLUCIBDEXMPDRVHJBIXHAMWEAVXEXRXFJJOEXCSLUHOQZGEYWTFKSYEAZEKJTJVFXUJSFSNNPCIALHAMWGFPFJBAZRBZJYKLZNDEQVUQJHBJKXDCDDRJGCFSVQIANJXKOMCFJDSQWOHQZDRPJNMIXKZBZFBGVIXIBWOOQWBDBQCIJMXCFOPIXNDCFILFJLZRBLTQHUUAUMJXGADHAQVQWZCXZVDSWTFSMQISVIOYTUYZCQWKIKDMEZCQWEQJBUCKZADOWZXSRKHHAEXEQJBILYKDBJIHAIOKQHAIXUCKZIQCFEXUCQRVXCYMUJOGGKZBZDFRLOBFJDSIFDRKPOGBDCROCVLNMIXLZSRKHMUKPSOOCXPVHVLXGUGEKVSMJYGPFCDMJLBJBMUHAWBUCQRWUFOAPYHNDCFWBDBQCAZWBVHYVANRIXZNFYKEAVXSMKGEXQOLUHOQICOAZBZYHALYIWQESMABJZXAZRPOQSBGFWBUUQIWQWGPIMARXFJJOEXCSLUHOQZGESRMJLBJBMUHAWBUCEUIXCSLBXPLXVDGZECYIKGFXLGLBXPVHIAVXYHULHAMWXZVHVKANWGNJWBJTDVEOHAWBUCAIYKXYCSIAJVNDRBKZVHLUHAMWLAANTFRICJPFLUUCKMWQBZCILGIXYSOQKRVXYHCAULDHDJAZIBHAOCDVEQJIIALUSOSBPLULANLQIXACOQMINNLUHASAHAVXWBVNJIAZMUWOMKHVALLCCSDIADUCGNDRMUOAZJIBHAIKLLSIPLULIJYHKSDOQICIPPOQSROBNUVXAPEXQGSMLUANHRWUUDVUQZNDGFHAYTFXGATAHAWBUCCOAYTAACXGIXHAQISCQVWBUUUCXEQDKHWAOQLZVNLUUCSXQVADYTDRCAYKXYNPNUOBVSDRKPHAVXWBANHRJGMXMJFJRIXZDOAYTALZHAQVXDJOEXHAGRKHKQXGEXHRJBQWDDYTECYKZWKUWBMINNVKQHEXQOZCDRVNMJZGIONTDBLBEXJTVKQMWBAZOPIXCAULMMMIYCGCZXWUUDJKEXDSGNALYIEOTFIBHACFQRCIWQRTIOZCCWPLVXRIIOHBCGCHIOYTMUULHASBWBTAIBEXHRJBUCYCDRVXOWJIAZUCAIPFAPEXCYJOQZDRJTJOOWVKYOJBSCADDBJIGMYKLUAZWUWLANMINNLUXZRIVXWBAZUCYPADAPKUSGLULXPSGUYKAYVLVXZGIXLACSSRIODBYOBDSAPLJBHAWBHAIXWAIXKQHAIXQYFXTFAZAZUCQRDRPAANJXDBMCIXAZIBVNJOQZDRRBWTSAEQJBOPIXIFJJJBLZWQXPUCQRMUTFXPZXJOXZTXXZIOHAUUOBALGFCNEPUGEYSBDBYNIOIKSWULJGCWTLGVUUCFRRANPPDRZXAPOGAZHAUUQGXPXDNNUBAZCFPLKRSRDRIFEPNJYTXZVDCFGCTXJJJBHAAZQIUBUTPLULIBRXFJJOEXCSLUHOQZGEAPYHNDCFEXHACFOCUNPJQRFXSFSROBDDBDQRWAFXLZJGYCPLCIGFSVAZRBZJYKKRULOCTFXPZJILANDFTFDSWWXYEXCYWUUDJKEXVHLUHAVXAZKEGHWBIXSNYKLUUCSXANVHWGVHLUKZWUBDAGYKIANNJDHHFXYCOCJODRGGSFSRQZDREOGNFXFEDRLBTFUCOLYHNDCFHLFYUPQRTFDSIFDRQOWQLUALJJPTUCOLYHNDCFBMGAWGDSEGIFADMUJOIXMZIXXZPZHAMWEAVXAPOGEXQOAFWMMUXDPVWLWBHDRBZJYKDVYPPVBPJBLXPLXJOQOAVXLBYYJVLZXZXPNDCFSCYTFXRIKHVXXPJOUCQRQIOWHBIJGISRAZUCSKJOMAAUFXUDBZDVANPPKRYYJKSNJTCFSMFJEBQWOHQZDRVNMJZGIONTDBTZDRVXOBQVNFYKEXHASOGFKQFEDRRZDVUUSAEBBPZCMKNNLUFJFELZWUBQXDJOHASOULMZKPWBADWDQZSWDBYIVXIBHAQVUDXYSBHAIBHAOCLGVXQWDRZJ'
for a in range(0,26):
        for b in range(0,26):
                for c in range(0,26):
                        for d in range(0,26):
                                stdout.write("\r %d %d %d %d" % (a,b,c,d))
                                decode = hill(inpt,a,b,c,d)
                                count = 0
                                for x in range(0,len(checklist)):
                                        if checklist[x] in decode:
                                                count+=1
                                if count >= 3:
                                        print(decode)
                                        q = input("Happy?")
