VISIBLE "GIMMEH COLOR"
GIMMEH COLOR
COLOR, WTF?
  IZ COLOR [OPERATOR] [VALUE]?
    VISIBLE "FISH NEEDZ COOKIN"
  OMG "YELLOW"
    VISIBLE ":{COLOR} FISH", GTFO
  OMG "GREEN"
    VISIBLE "FISH HAS A FLAVOR", GTFO
  OMGWTF
    VISIBLE "FISH IS INVISIBLES"
OIC
